version: '2'

services:

  nginx:
    image: nginx
    command: /bin/bash -c "envsubst '$$VIRTUAL_HOST $$VIRTUAL_PORT' < /etc/nginx/conf.d/ofn.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    expose: [ "80" ]
    links: 
      - web
    environment:
      VIRTUAL_HOST: "ofn.allmende.io"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "ofn.allmende.io"
      LETSENCRYPT_EMAIL: "text@allmende.io"
    volumes:
      - ./nginx/ofn.template:/etc/nginx/conf.d/ofn.template
    volumes_from:
      - web:ro
    networks:
      - frontend
      - backend

  web:
    build: .
    command: bundle exec unicorn -E production -p 3000 -c ./config/unicorn.rb
    expose:
      - "3000"
    environment:
      DATABASE_URL: "postgresql://ofn:tusheihei3Soarah9Ahdie8Uiquo0wel@postgresql/ofn"
      RAILS_ENV: "production"
    volumes:
      - ./application.yml:/ofn/config/application.yml
      - ./public:/ofn/public
    links:
      - postgresql
    networks:
      - backend
#    restart: always

# is there a docu of this tmux setup? keybindings, etc.

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "tusheihei3Soarah9Ahdie8Uiquo0wel"
      POSTGRES_USER: "ofn"
    volumes:
      - ./postgresql/:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

networks:
  frontend:
    external:
      name: nginx_frontend

  backend:
    driver: bridge
